services:

  postgres:
    image: postgres:16-alpine
    container_name: istrazidomace-postgres
    environment:
      POSTGRES_DB: istrazidomace
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - istrazidomace-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: istrazidomace-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - istrazidomace-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
  redis_data:

networks:
  istrazidomace-network:
    driver: bridge